### PR TITLE
Few fixes and translation update

### PR DESCRIPTION
**Pull request by Blueberryy**
- Replaced links to some contributors with permanent links.
- Added "various people" string for guide book.
- Updated russian translation.
- Apply spectator team name translation.

### CODE REVIEW

**Comment by Piengineer12** [comment]
I have made an update so that if a token like "rotgb.guide.description" is missing, it checks and concatenates "rotgb.guide.description.1", "rotgb.guide.description.2", etc. But you still need to put %n for newlines.

Also it turns out I was stupid and forgot to update the codes on GitHub. Can I help to add commits here for the files to match the latest version?

**Comment by Blueberryy** [comment]
idk

**Comment by Blueberryy** [comment]
sure

**Review by Piengineer12 — COMMENTED** [review]
I've looked at and tested the files, only rotgb_tg_misc needs to be updated - rotgb_tg.welcome and rotgb_tg.help has some updated English text that needs to be translated. Thank you very much for helping with the rest!

**Comment by Piengineer12** [comment]
I've just realized that I had left this open, oops!
That said, could you update rotgb_tg_misc.properties to match the latest version after this?

**Pull request merged**
